/**
 * Creates an object map with the same keys as `map` and values generated by
 * running each value of `record` thru `fn`.
 */
export function mapValue<T, V>(
  record: Record<string, T>,
  fn: (value: T, key: string) => V
): Record<string, V> {
  const result = Object.create(null)

  for (const key of Object.keys(record)) {
    result[key] = fn(record[key], key)
  }
  return result
}

// https://github.com/graphql/graphql-js/blob/main/src/jsutils/toObjMap.ts
export function toObjMap<T>(
  obj: Maybe<ReadOnlyObjMapLike<T>>
): ReadOnlyObjMap<T> {
  if (obj == null) {
    return Object.create(null)
  }

  if (Object.getPrototypeOf(obj) === null) {
    return obj
  }

  const map = Object.create(null)
  for (const [key, value] of Object.entries(obj)) {
    map[key] = value
  }
  return map
}

export function notNullish<T>(x: T | undefined | null): x is T {
  return x != null
}

type Maybe<T> = null | undefined | T

type ReadOnlyObjMapLike<T> = ReadOnlyObjMap<T> | { readonly [key: string]: T }

interface ReadOnlyObjMap<T> {
  readonly [key: string]: T
}
